/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:f83edc4c-3090-4c76-aad8-94acb64a3802",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_jlXwUPCJP",
    "aws_user_pools_web_client_id": "235f3nj0va9t16ftj951dps361",
    "oauth": {}
};


export default awsmobile;
